apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendations-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendations
  template:
    metadata:
      labels:
        app: recommendations
    spec:
      containers:
      - image: mu2729/streaming-recommendations
        name: recommendations
        env:
        - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
          value: http://etcd:2379
        - name: KUMULUZEE_CONFIG_ETCD_HOSTS
          value: http://etcd:2379
        - name: KUMULUZEE_SERVER_HTTP_PORT
          value: "8080"
        - name: KUMULUZEE_SERVER_BASE-URL
          value: http://159.122.186.127:30729
        - name: KUMULUZEE_HEALTH_CHECKS_ETCDHEALTHCHECK_CONNECTIONURL
            value: http://etcd:2379/health
        ports:
        - containerPort: 8080
          protocol: TCP
          name: recommendations-port
        livenessProbe:
          httpGet:
            path: /health
            port: recommendations-port
          initialDelaySeconds: 30
          periodSeconds: 3
---

apiVersion: v1
kind: Service
metadata:
  name: recommendations
spec:
  type: NodePort
  selector:
    app: recommendations
  ports:
  - protocol: TCP
    port: 8083
    targetPort: 8080